export enum BodyZone {
    // Zones générales
    TOUTE_ZONE = 'TOUTE_ZONE',

    // Visage
    VISAGE_COMPLET = 'VISAGE_COMPLET',
    INTER_SOURCILIER = 'INTER_SOURCILIER',
    LEVRE_SUPERIEURE = 'LEVRE_SUPERIEURE',
    MENTON = 'MENTON',
    POMMETTES = 'POMMETTES',
    FRONT = 'FRONT',
    SOURCILS = 'SOURCILS',
    PAUPIERES = 'PAUPIERES',
    RIDE_DU_LION = 'RIDE_DU_LION',
    OVALE_DU_VISAGE = 'OVALE_DU_VISAGE',
    PATTE_DOIE = 'PATTE_DOIE',
    CONTOUR_DE_LA_BOUCHE = 'CONTOUR_DE_LA_BOUCHE',
    DOUBLE_MENTON = 'DOUBLE_MENTON',
    MOUSTACHE = 'MOUSTACHE',

    // Corps
    COU = 'COU',
    NUQUE = 'NUQUE',
    ECHANCRE_MAINTENANT = 'ECHANCRE_MAINTENANT',
    AISSSELLES = 'AISSSELLES',
    AVANT_BRAS = 'AVANT_BRAS',
    BRAS_ENTIERS = 'BRAS_ENTIERS',
    DOS_COMPLET = 'DOS_COMPLET',
    HAUT_DU_DOS = 'HAUT_DU_DOS',
    EPAULES = 'EPAULES',
    TORSE = 'TORSE',
    BAS_DU_DOS = 'BAS_DU_DOS',
    VENTRE = 'VENTRE',
    SEINS = 'SEINS',
    FESSES = 'FESSES',
    CUISSES_COMPLETES = 'CUISSES_COMPLETES',
    CUISSES = 'CUISSES',
    GENOUX = 'GENOUX',
    POIGNET_D_AMOUR = 'POIGNET_D_AMOUR',
    MAINS = 'MAINS',
    COUDES = 'COUDES',
    PIEDS = 'PIEDS',
    CORPS_ENTIER = 'CORPS_ENTIER',
    FLANCS = 'FLANCS',

    // Zones spécifiques aux jambes
    DEMI_JAMBES = 'DEMI_JAMBES',
    JAMBES_ENTIERES = 'JAMBES_ENTIERES',

    // Zones spécifiques au maillot
    MAILLOT_INTEGRAL = 'MAILLOT_INTEGRAL',
    MAILLOT_ECHANCRE = 'MAILLOT_ECHANCRE',

    // Zones spécifiques pour les hommes
    BARBE_ENTIERE = 'BARBE_ENTIERE',
    COLLIER_DE_BARBE = 'COLLIER_DE_BARBE',

    // Autres zones
    SIF = 'SIF',
    BOURRELETS_DOS = 'BOURRELETS_DOS',
    INTERIEURE_CUISSES = 'INTERIEURE_CUISSES',
    DECLOLETE = 'DECLOLETE',
    RIDE_LION = 'RIDE_LION',
    BAS_VENTRE = 'BAS_VENTRE',

    // Combinaisons de zones
    VISAGE_ET_COUP = 'VISAGE_ET_COUP',
    AISSSELLES_ET_DEMI_JAMBES = 'AISSSELLES_ET_DEMI_JAMBES',
    AISSSELLES_ET_JAMBES_ENTIERES = 'AISSSELLES_ET_JAMBES_ENTIERES',
    AISSSELLES_ET_MAINTENANT = 'AISSSELLES_ET_MAINTENANT',
    DOS_ET_EPAULES = 'DOS_ET_EPAULES',
    COU_ET_NUQUE = 'COU_ET_NUQUE',
    DEMI_JAMBES_ET_PIEDS = 'DEMI_JAMBES_ET_PIEDS',
    HAUT_DU_DOS_ET_EPAULES = 'HAUT_DU_DOS_ET_EPAULES',
    MAINTENANT_ET_AISSSELLES = 'MAINTENANT_ET_AISSSELLES',
    VISAGE_COMPLET_ET_COUP = 'VISAGE_COMPLET_ET_COUP',
    PATTE_DOIE_ET_RIDE_DU_LION = 'PATTE_DOIE_ET_RIDE_DU_LION',
    MAILLOT_INTEGRAL_ET_AISSSELLES = 'MAILLOT_INTEGRAL_ET_AISSSELLES'
}
