export enum BeautyCareMachine {
    CRYO_SCULPTOR = 'CRYO_SCULPTOR',
    ELECTROLYSE = 'ELECTROLYSE',
    IPL_EPIL_EXPERT_2_0 = 'IPL_EPIL_EXPERT_2_0',
    HIFEM_SCULPT = 'HIFEM_SCULPT',
    HIFU_LIFT_3D = 'HIFU_LIFT_3D',
    LIFT_AND_SCULPT_CORPS = 'LIFT_AND_SCULPT_CORPS',
    LIFT_AND_SCULPT_VISAGE = 'LIFT_AND_SCULPT_VISAGE',
    WISHPROPLUS = 'WISHPROPLUS',
    LED_NEW_LIGHT_22_MEDICAL = 'LED_NEW_LIGHT_22_MEDICAL',
    HYDROJET_JETPEEL = 'HYDROJET_JETPEEL',
    CATIO_VITAL = 'CATIO_VITAL',
    NONE = 'NONE'
}
