export enum CareCategory {
    CONSULTATION = 'CONSULTATION',
    EPILATION_HOMME = 'EPILATION_HOMME',
    EPILATION_FEMME = 'EPILATION_FEMME',
    SOIN_AMINCISSANT_RAFFERMISSANT = 'SOIN_AMINCISSANT_RAFFERMISSANT',
    SOIN_PEAU = 'SOIN_PEAU',
    SOIN_VISAGE = 'SOIN_VISAGE',
    MANUCURE_PEDICURE = 'MANUCURE_PEDICURE',
    MAQUILLAGE = 'MAQUILLAGE',
    MASSAGE = 'MASSAGE'
}