
export enum SymbolKey {
  BTCUSDT = 'btcusdt',
  ETHUSDT = 'ethusdt',
  XRPUSDT = 'xrpusdt',
  LTCUSDT = 'ltcusdt',
  ADAUSDT = 'adausdt',
  DOGEUSDT = 'dogeusdt',
  SOLUSDT = 'solusdt',
  BNBUSDT = 'bnbusdt',
  DOTUSDT = 'dotusdt',
  TRXUSDT = 'trxusdt',
  AVAXUSDT = 'avaxusdt',
  USDCUSDT = 'usdcusdt',
  SHIBUSDT = 'shibusdt',
  MATICUSDT = 'maticusdt',
  WIFUSDT = 'wifusdt',
  PEPEUSDT = 'pepeusdt',
  NEARUSDT = 'nearusdt',
  FTTUSDT = 'fttusdt',
  LINKUSDT = 'linkusdt',
  ATOMUSDT = 'atomusdt',
  UNIUSDT = 'uniusdt',
  XLMUSDT = 'xlmusdt',
  BCHUSDT = 'bchusdt',
  ETCUSDT = 'etcusdt',
  ALGOUSDT = 'algousdt',
  FLOWUSDT = 'flowusdt',
  VETUSDT = 'vetusdt',
  APEUSDT = 'apeusdt',
  ICPUSDT = 'icpusdt',
  MANAUSDT = 'manausdt',
  SANDUSDT = 'sandusdt',
  FILUSDT = 'filusdt',
  XTZUSDT = 'xtzusdt',
  HBARUSDT = 'hbarusdt',
  THETAUSDT = 'thetausdt',
  EGLDUSDT = 'egldusdt',
  AXSUSDT = 'axsusdt',
  EOSUSDT = 'eosusdt',
  AAVEUSDT = 'aaveusdt',
  QNTUSDT = 'qntusdt',
  TUSDUSDT = 'tusdusdt',
  MKRUSDT = 'mkrusdt',
  ZECUSDT = 'zecusdt',
  CHZUSDT = 'chzusdt',
  RUNEUSDT = 'runeusdt',
  GRTUSDT = 'grtusdt',
  KLAYUSDT = 'klayusdt',
  SNXUSDT = 'snxusdt',
  FTMUSDT = 'ftmusdt',
  CAKEUSDT = 'cakeusdt',
  NEOUSDT = 'neousdt',
  WAVESUSDT = 'wavesusdt',
  OSMOUSDT = 'osmousdt',
  ARUSDT = 'arusdt',
  LRCUSDT = 'lrcusdt',
  DASHUSDT = 'dashusdt',
  ENJUSDT = 'enjusdt',
  KSMUSDT = 'ksmusdt',
  XECUSDT = 'xecusdt',
  GALAUSDT = 'galausdt',
  AMPUSDT = 'ampusdt',
  ONEUSDT = 'oneusdt',
  ZILUSDT = 'zilusdt',
  CRVUSDT = 'crvusdt',
  MINAUSDT = 'minausdt',
  DCRUSDT = 'dcrusdt',
  CELOUSDT = 'celousdt',
  NEXOUSDT = 'nexousdt',
  STXUSDT = 'stxusdt',
  KDAUSDT = 'kdausdt',
  COMPUSDT = 'compusdt',
  INCHUSDT = '1inchusdt',
  CVXUSDT = 'cvxusdt',
  TFUELUSDT = 'tfuelusdt',
  HOTUSDT = 'hotusdt',
  OMGUSDT = 'omgusdt',
  ROSEUSDT = 'roseusdt',
  QTUMUSDT = 'qtumusdt',
  RVNUSDT = 'rvnusdt',
  ICXUSDT = 'icxusdt',
  AUDIOUSDT = 'audiousdt',
  GLMRUSDT = 'glmrusdt',
  ANKRUSDT = 'ankrusdt'
}

export const SYMBOLS_INFO: Record<SymbolKey, { name: string; acronym: string }> = {
  [SymbolKey.BTCUSDT]: { name: "Bitcoin", acronym: "BTC" },
  [SymbolKey.ETHUSDT]: { name: "Ethereum", acronym: "ETH" },
  [SymbolKey.XRPUSDT]: { name: "Ripple", acronym: "XRP" },
  [SymbolKey.LTCUSDT]: { name: "Litecoin", acronym: "LTC" },
  [SymbolKey.ADAUSDT]: { name: "Cardano", acronym: "ADA" },
  [SymbolKey.DOGEUSDT]: { name: "Dogecoin", acronym: "DOGE" },
  [SymbolKey.SOLUSDT]: { name: "Solana", acronym: "SOL" },
  [SymbolKey.BNBUSDT]: { name: "Binance Coin", acronym: "BNB" },
  [SymbolKey.DOTUSDT]: { name: "Polkadot", acronym: "DOT" },
  [SymbolKey.TRXUSDT]: { name: "Tron", acronym: "TRX" },
  [SymbolKey.AVAXUSDT]: { name: "Avalanche", acronym: "AVAX" },
  [SymbolKey.USDCUSDT]: { name: "USD Coin", acronym: "USDC" },
  [SymbolKey.SHIBUSDT]: { name: "Shiba Inu", acronym: "SHIB" },
  [SymbolKey.MATICUSDT]: { name: "Polygon", acronym: "MATIC" },
  [SymbolKey.WIFUSDT]: { name: "Wifedoge", acronym: "WIFE" },
  [SymbolKey.PEPEUSDT]: { name: "Pepe", acronym: "PEPE" },
  [SymbolKey.NEARUSDT]: { name: "Near Protocol", acronym: "NEAR" },
  [SymbolKey.FTTUSDT]: { name: "FTX Token", acronym: "FTT" },
  [SymbolKey.LINKUSDT]: { name: "Chainlink", acronym: "LINK" },
  [SymbolKey.ATOMUSDT]: { name: "Cosmos", acronym: "ATOM" },
  [SymbolKey.UNIUSDT]: { name: "Uniswap", acronym: "UNI" },
  [SymbolKey.XLMUSDT]: { name: "Stellar", acronym: "XLM" },
  [SymbolKey.BCHUSDT]: { name: "Bitcoin Cash", acronym: "BCH" },
  [SymbolKey.ETCUSDT]: { name: "Ethereum Classic", acronym: "ETC" },
  [SymbolKey.ALGOUSDT]: { name: "Algorand", acronym: "ALGO" },
  [SymbolKey.FLOWUSDT]: { name: "Flow", acronym: "FLOW" },
  [SymbolKey.VETUSDT]: { name: "VeChain", acronym: "VET" },
  [SymbolKey.APEUSDT]: { name: "ApeCoin", acronym: "APE" },
  [SymbolKey.ICPUSDT]: { name: "Internet Computer", acronym: "ICP" },
  [SymbolKey.MANAUSDT]: { name: "Decentraland", acronym: "MANA" },
  [SymbolKey.SANDUSDT]: { name: "The Sandbox", acronym: "SAND" },
  [SymbolKey.FILUSDT]: { name: "Filecoin", acronym: "FIL" },
  [SymbolKey.XTZUSDT]: { name: "Tezos", acronym: "XTZ" },
  [SymbolKey.HBARUSDT]: { name: "Hedera", acronym: "HBAR" },
  [SymbolKey.THETAUSDT]: { name: "Theta", acronym: "THETA" },
  [SymbolKey.EGLDUSDT]: { name: "Elrond", acronym: "EGLD" },
  [SymbolKey.AXSUSDT]: { name: "Axie Infinity", acronym: "AXS" },
  [SymbolKey.EOSUSDT]: { name: "EOS", acronym: "EOS" },
  [SymbolKey.AAVEUSDT]: { name: "Aave", acronym: "AAVE" },
  [SymbolKey.QNTUSDT]: { name: "Quant", acronym: "QNT" },
  [SymbolKey.TUSDUSDT]: { name: "TrueUSD", acronym: "TUSD" },
  [SymbolKey.MKRUSDT]: { name: "Maker", acronym: "MKR" },
  [SymbolKey.ZECUSDT]: { name: "Zcash", acronym: "ZEC" },
  [SymbolKey.CHZUSDT]: { name: "Chiliz", acronym: "CHZ" },
  [SymbolKey.RUNEUSDT]: { name: "Thorchain", acronym: "RUNE" },
  [SymbolKey.GRTUSDT]: { name: "The Graph", acronym: "GRT" },
  [SymbolKey.KLAYUSDT]: { name: "Klaytn", acronym: "KLAY" },
  [SymbolKey.SNXUSDT]: { name: "Synthetix", acronym: "SNX" },
  [SymbolKey.FTMUSDT]: { name: "Fantom", acronym: "FTM" },
  [SymbolKey.CAKEUSDT]: { name: "PancakeSwap", acronym: "CAKE" },
  [SymbolKey.NEOUSDT]: { name: "Neo", acronym: "NEO" },
  [SymbolKey.WAVESUSDT]: { name: "Waves", acronym: "WAVES" },
  [SymbolKey.OSMOUSDT]: { name: "Osmosis", acronym: "OSMO" },
  [SymbolKey.ARUSDT]: { name: "Arweave", acronym: "AR" },
  [SymbolKey.LRCUSDT]: { name: "Loopring", acronym: "LRC" },
  [SymbolKey.DASHUSDT]: { name: "Dash", acronym: "DASH" },
  [SymbolKey.ENJUSDT]: { name: "Enjin Coin", acronym: "ENJ" },
  [SymbolKey.KSMUSDT]: { name: "Kusama", acronym: "KSM" },
  [SymbolKey.XECUSDT]: { name: "eCash", acronym: "XEC" },
  [SymbolKey.GALAUSDT]: { name: "Gala", acronym: "GALA" },
  [SymbolKey.AMPUSDT]: { name: "Amp", acronym: "AMP" },
  [SymbolKey.ONEUSDT]: { name: "Harmony", acronym: "ONE" },
  [SymbolKey.ZILUSDT]: { name: "Zilliqa", acronym: "ZIL" },
  [SymbolKey.CRVUSDT]: { name: "Curve DAO Token", acronym: "CRV" },
  [SymbolKey.MINAUSDT]: { name: "Mina", acronym: "MINA" },
  [SymbolKey.DCRUSDT]: { name: "Decred", acronym: "DCR" },
  [SymbolKey.CELOUSDT]: { name: "Celo", acronym: "CELO" },
  [SymbolKey.NEXOUSDT]: { name: "Nexo", acronym: "NEXO" },
  [SymbolKey.STXUSDT]: { name: "Stacks", acronym: "STX" },
  [SymbolKey.KDAUSDT]: { name: "Kadena", acronym: "KDA" },
  [SymbolKey.COMPUSDT]: { name: "Compound", acronym: "COMP" },
  [SymbolKey.INCHUSDT]: { name: "1inch", acronym: "1INCH" },
  [SymbolKey.CVXUSDT]: { name: "Convex Finance", acronym: "CVX" },
  [SymbolKey.TFUELUSDT]: { name: "Theta Fuel", acronym: "TFUEL" },
  [SymbolKey.HOTUSDT]: { name: "Holo", acronym: "HOT" },
  [SymbolKey.OMGUSDT]: { name: "OMG Network", acronym: "OMG" },
  [SymbolKey.ROSEUSDT]: { name: "Oasis Network", acronym: "ROSE" },
  [SymbolKey.QTUMUSDT]: { name: "Qtum", acronym: "QTUM" },
  [SymbolKey.RVNUSDT]: { name: "Ravencoin", acronym: "RVN" },
  [SymbolKey.ICXUSDT]: { name: "ICON", acronym: "ICX" },
  [SymbolKey.AUDIOUSDT]: { name: "Audius", acronym: "AUDIO" },
  [SymbolKey.GLMRUSDT]: { name: "Moonbeam", acronym: "GLMR" },
  [SymbolKey.ANKRUSDT]: { name: "Ankr", acronym: "ANKR" }
};

